.github/ISSUES_TEMPLATE/bug_report.md, .github/ISSUES_TEMPLATE/sub_task.md
Templates for bugs and sub-tasks as per #38
=> issue_templates

src/sql/install.sh, src/sql/install_web.sh
Otherwise it exits with a successful status even when
things go extremely wrong...
=> Have install.sh properly report failures

src/NZGBplugin/docker-compose.yml
See https://github.com/linz/ds-group-epics/issues/95
=> WIP: Add docker-compose configuration

.github/workflows/ci-db.yml, src/sql/Dockerfile, src/sql/Makefile
=> Dockerize gazzetteer db

INSTALLATION
=> Improve formatting of docs, specify min PostgreSQL version

src/NZGBplugin/Plugin.py
=> Improve About screen reporting, evidencing when there's no connection

CONTRIBUTING.md, README.md
Fixes: #  
#87 add details of running commit message checks locally
=> docs: git-msg git-hook doc #87

.github/workflows/push.yml, .gitlint, .pre-commit-config.yaml, README.md, requirements-dev.txt
Fixes: #  
#40 -  enforce conventional commits
* conventional commit configuration 
* github action to run conventionalcommit validation
Github action will test commit
=> chore: enforce conventional commits #40

.docker/qgis/scripts/docker-entry.sh, .docker/qgis/scripts/enable_nzgbplugin, .docker/qgis/scripts/startup.py, src/NZGBplugin/Dockerfile, src/NZGBplugin/LINZ/gazetteer/gui/DatabaseConfiguration.py
Resolves CI `ImportError: cannot import name 'Config'` error
=> Startup #99

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/sub_task.md
Fixes: # 114
- Added a github template for new features.
- Improved formatting of other templates
- n/a README updated (where applicable)
- n/a CHANGELOG updated
- n/a Confluence user guide updated (where applicable)
- n/a Added tests that fail without this change
- n/a All tests are passing in development environment
- n/a Linked to the epic
=> Feature issue template

README.md
Fixes: # 121
- Fixed typo #121 
- Fixed some other formatting issues
- Clarified some sentences
Read it
=> docs: update README - fixes #121

src/NZGBplugin/Dockerfile
Fixes: #
#123
upgrade sqlalchemy version
Let CI do it's thing
=> fixes app start issue #123

src/NZGBplugin/Dockerfile
To help with testing new upstreams
=> feat: add support for UPSTREAM_TAG docker build arg

src/NZGBplugin/GazEditForms.py, src/NZGBplugin/Layers.py
Fixes: #
* #158
* #156 
Associates UI Edit Form to layer. Associated UI Form code populated required IDs. 
Unit tests being developed for this workflow. 
Manual testing proves this resolves the issue. The now needs to be merged into the testing branch
=> config EditForm

src/NZGBplugin/tests/test_search.py
Fixes: #
adding in search functionality tests
adding in search functionality tests
tests will not pass as DB changes (#166) are required
...
=> search tests

src/NZGBplugin/GazEditForms.py, src/NZGBplugin/Layers.py, src/NZGBplugin/Plugin.py, src/NZGBplugin/tests/test_edit_geom.py, src/NZGBplugin/tests/test_new_feature.py, src/NZGBplugin/tests/utils/data_handler.py, src/sql/gazetteer_geometry_views.sql
Fixes: 
Predominately addresses epic [#139](https://github.com/linz/ds-group-epics/issues/139)
But also address editing functionality where porting missed API breakages 
* #167
* #168
* #168
Let automated tests run
=> Tests edit geom

src/sql/gazetteer_lol_extract_view.sql, src/sql/install.sh
Fixes: #
#178 
installs missing name_export_for_lol view that the gaz_update_export_database function depends on
...
=> install name_export_for_lol

Makefile
It needed quoting, or would connect to "postgres" database
=> fix: `docker-db-connect` Makefile target database specification

Makefile, docker-compose.yml, src/NZGBplugin/LINZ/Widgets/ListModelConnector.py, src/NZGBplugin/Plugin.py, src/NZGBplugin/tests/test_admin_interface.py, src/NZGBplugin/tests/test_new_feature.py, src/NZGBplugin/tests/utils/config.ini
Fixes: #
#153 Write tests for test plan number 4 (admin panel)
#187 Sorting of system codes fail bug 
...
CI must pass
=> admin test

src/NZGBplugin/metadata.txt
=> update the release version

src/sql/gazetteer_app_sysdata.sql
Fixes: #
The database and metadata.txt versions must match. 
...
...
=> update DB version

src/NZGBplugin/Layers.py
Fixes: #
#218
handle removal of multi-geoms
...
...
=> update layer feat geom to multi

src/NZGBplugin/NewFeatureDialog.py, src/NZGBplugin/Ui_NewFeatureDialog.py, src/NZGBplugin/Ui_NewFeatureDialog.ui, src/NZGBplugin/tests/test_edit_geom.py, src/NZGBplugin/tests/test_new_feature.py
=> ensure newfeat dlg is modal

src/NZGBplugin/LINZ/gazetteer/gui/html/js/name.js
=> Resolve assoc href

src/NZGBplugin/LINZ/gazetteer/Model.py
Fixes: #
_Add new line for each issue that was fixed_
...
...
=> astext > st_astext

src/NZGBplugin/Layers.py, src/NZGBplugin/metadata.txt, src/sql/gazetteer_app_sysdata.sql
Fixes: #
#222 
resolves the duplicating of layers
...
=> fix: duplicating layers #222

.github/workflows/ci.yml, docker-compose.yml, src/sql/Dockerfile, src/sql/Makefile
Provide makefile targets to build db version 12 (with postgis 3.0)
=> Add PostgreSQL 12 support

src/sql/Dockerfile
Fixes: #
_Add new line for each issue that was fixed_
Updates the default docker versions for postgres and postgis to the current production versions
...
...
=> Update default docker versions

src/sql/test/schema/schema.sql
Fixes: # 257
Add owner test for gazetteer_export schema
...
...
=> fix: owner for gazetteer_export schema

CHANGELOG.md, src/NZGBplugin/LINZ/gazetteer/Database.py, src/NZGBplugin/metadata.txt, src/sql/gazetteer_app_sysdata.sql
=> Db host update

.github/workflows/ci.yml
=> Improve CI runs

src/NZGBplugin/LINZ/Util/pyratemp.py, src/NZGBplugin/LINZ/Widgets/WidgetConnector.py, src/NZGBplugin/LINZ/gazetteer/Export.py, src/NZGBplugin/Layers.py, src/NZGBplugin/tests/test_search.py, src/sql/install_web_config.py
Fixes: #
linting and upgrading to python3
...
...
=> Python 2 to 3

CHANGELOG.md, src/NZGBplugin/metadata.txt, src/sql/gazetteer_app_sysdata.sql
=> Deploy #260 to production plugin repository

CHANGELOG.md, src/NZGBplugin/metadata.txt, src/sql/gazetteer_app_sysdata.sql
Fixes: #260 by deploying to production
...
...
=>  v2.1.1 release
